name: buycar
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <3.22.2"
  flutter: 3.10.0

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^5.2.0
  firebase_core: 
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^8.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/data/